FROM node:20-alpine

WORKDIR /workspace

COPY repo/backend/package*.json ./backend/
COPY repo/frontend/package*.json ./frontend/
RUN cd backend && npm install
RUN cd frontend && npm install --legacy-peer-deps

COPY repo/backend ./backend
COPY repo/frontend ./frontend
COPY docs ./docs

CMD ["sh", "-c", "cd backend && npm run test && cd ../frontend && npm run test"]
